### ISSUE TITLE
How to add headers

### ISSUE THREAD

**Issue by mmustala** [a2800276/8583#17]
Hi,

How could I add headers (H1 to H14) into the message? Is there a way to use the existing code or would it need some new code to support header fields?

Basically the message I would need to build should have structure like this:
MTI
Bitmap, Primary
Bitmap, Secondary
Bitmap, Third
H1
...
H14
2
...
127.L3

**Comment by a2800276** [comment]
Hi Mika,

I'm a bit confused, could you provide some more information, e.g. the specific protocol you're working with? In general there is no third bitmap in 8583 and I'm not sure I understand what you mean with "header fields", though that might just be a case of your protocols specific jargon.

If you'd like you can get in touch directly (tim@presseverykey.com)

**Comment by mmustala** [comment]
Hi,

The headers may be specific to our case. I actually already modified the gem to support the headers the way that I see they should be used in our case. We'll see how it works.

Thanks

**Comment by a2800276** [comment]
ok, good to hear, let me know in case anything else comes up. I'll go ahead and close this.
