### ISSUE TITLE
Noisy output from deprecated fixnum

### ISSUE THREAD

**Issue by absrd** [a2800276/8583#22]
/ruby/2.4.0/gems/iso8583-0.2.2/lib/iso8583/field.rb:70: warning: constant ::Fixnum is deprecated
/ruby/2.4.0/gems/iso8583-0.2.2/lib/iso8583/field.rb:22: warning: constant ::Fixnum is deprecated

**Comment by a2800276** [comment]
Any suggestions? Do you have any experience in how to do this in a backwards compatible manner? Would replacing `Fixnum` with `Integer` be sufficient to cover all cases?

**Comment by absrd** [comment]
Integer has been a super class at least since 1.8.7.

It shouldn't be problem just replacing them with Integer, unless earlier versions are supported.

**Comment by a2800276** [comment]
Good to know, thanks. Were you planning to provide a pull request?

**Comment by absrd** [comment]
No. I don't the PR procedures of the project with regards to versioning and what else, so only if someone else can't make quick PR.

**Comment by a2800276** [comment]
There's not programming handbook for this project :) You seem to have a good grasp of the consequences, so if you want/need the chagnes quickly, I'd certainly appreciate a PR. But it's fine if you don't, but I can only gurantee doing it "when I get around to it". Either way, thanks for the heads-up!
